//products
const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";
//categories
const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";
//categorie products
const GET_CATEGORY_PRODUCTS_REQUEST = "GET_CATEGORY_PRODUCTS_REQUEST";
const GET_CATEGORY_PRODUCTS_SUCCESS = "GET_CATEGORY_PRODUCTS_SUCCESS";
const GET_CATEGORY_PRODUCTS_FAILURE = "GET_CATEGORY_PRODUCTS_FAILURE";
export const types = {
  //products
  GET_PRODUCTS_REQUEST,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAILURE,
  //categories
  GET_CATEGORIES_REQUEST,
  GET_CATEGORIES_SUCCESS,
  GET_CATEGORIES_FAILURE,
  //category products
  GET_CATEGORY_PRODUCTS_REQUEST,
  GET_CATEGORY_PRODUCTS_SUCCESS,
  GET_CATEGORY_PRODUCTS_FAILURE,
};
