const SHOW_SPINNER = "SHOW_SPINNER";
const HIDE_SPINNER = "HIDE_SPINNER";
const SET_ACTIVE_LANGUAGE = "SET_ACTIVE_LANGUAGE";

export const types = {
  SHOW_SPINNER,
  HIDE_SPINNER,
  SET_ACTIVE_LANGUAGE,
};
